import { ReactNode } from "react";
import { OpenAlexWorkType } from "../types/openalex";
import { IconAppWindow, IconBan, IconBook2, IconBooks, IconCertificate, IconClipboardText, IconClock, IconCode, IconCompass, IconCpu, IconDatabase, IconFile, IconFilePencil, IconFlask, IconFrame, IconMail, IconNews, IconNotebook, IconPaperclip, IconPresentation, IconSchool, IconSourceCode, IconTable, IconTool, IconUserCheck } from "@tabler/icons-react";

export const OPENALEX_WORK_TYPE_LABELS = {
  journal_article: "Journal Article",
  book: "Book",
  book_chapter: "Book Chapter",
  book_review: "Book Review",
  conference_abstract: "Conference Abstract",
  conference_paper: "Conference Paper",
  data_paper: "Data Paper",
  dataset: "Dataset",
  dissertation: "Thesis / Dissertation",
  editorial: "Editorial",
  erratum: "Erratum",
  letter: "Letter",
  libguides: "LibGuide",
  other: "Other",
  paratext: "Paratext",
  peer_review: "Peer Review",
  preprint: "Preprint",
  reference_entry: "Reference Entry",
  technical_report: "Report / Working Paper",
  retraction: "Retraction",
  review_article: "Review Article",
  software: "Software",
  software_paper: "Software Paper",
  standard: "Standard",
  supplementary_materials: "Supplementary Materials",
} as const;

export const OPENALEX_TYPE_MAP: Record<string, OpenAlexWorkType> = {
  "article": "journal_article",
  "book": "book",
  "book-chapter": "book_chapter",
  "book-review": "book_review",
  "conference-abstract": "conference_abstract",
  "conference-paper": "conference_paper",
  "data-paper": "data_paper",
  "dataset": "dataset",
  "dissertation": "dissertation",
  "editorial": "editorial",
  "erratum": "erratum",
  "letter": "letter",
  "libguides": "libguides",
  "other": "other",
  "paratext": "paratext",
  "peer-review": "peer_review",
  "preprint": "preprint",
  "reference-entry": "reference_entry",
  "technical-report": "technical_report",
  "retraction": "retraction",
  "review": "review_article",
  "software": "software",
  "software-paper": "software_paper",
  "standard": "standard",
  "supplementary-materials": "supplementary_materials",
}

export const PUB_PRODUCT_TYPE_ICON_PROPS = { size: "0.85rem", color: "var(--mantine-color-indigo-8)" };

export const PUB_PRODUCT_TYPE_ICONS: Record<OpenAlexWorkType | string, ReactNode> = {
  journal_article: <IconNotebook {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  book: <IconBook2 {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  book_chapter: <IconBook2 {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  book_review: <IconBook2 {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  conference_abstract: <IconPresentation {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  conference_paper: <IconPresentation {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  data_paper: <IconDatabase {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  dataset: <IconDatabase {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  dissertation: <IconSchool {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  editorial: <IconNews {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  erratum: <IconFilePencil {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  letter: <IconMail {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  libguides: <IconCompass {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  other: <IconFile {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  paratext: <IconFrame {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  peer_review: <IconUserCheck {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  preprint: <IconClock {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  reference_entry: <IconTable {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  technical_report: <IconClipboardText {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  retraction: <IconBan {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  review_article: <IconBooks {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  software: <IconCode {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  software_paper: <IconSourceCode {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  standard: <IconCertificate {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  supplementary_materials: <IconPaperclip {...PUB_PRODUCT_TYPE_ICON_PROPS}/>,
  tool: <IconTool {...PUB_PRODUCT_TYPE_ICON_PROPS} />,
  ai_tool: <IconCpu {...PUB_PRODUCT_TYPE_ICON_PROPS} />,
  platform: <IconAppWindow {...PUB_PRODUCT_TYPE_ICON_PROPS} />,
  simulation: <IconFlask {...PUB_PRODUCT_TYPE_ICON_PROPS} />,
};

export const OPENALEX_TYPE_VALUES = Object.keys(OPENALEX_WORK_TYPE_LABELS) as OpenAlexWorkType[];
